# Generated by Django 5.2.8 on 2025-12-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_usertrainingprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrainingprogress',
            name='checked_items',
        ),
        migrations.AddField(
            model_name='usertrainingprogress',
            name='progress_by_popup',
            field=models.JSONField(default=dict),
        ),
    ]
