# Generated by Django 5.1 on 2025-12-09 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
