# Generated by Django 5.1 on 2025-12-09 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_user_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='defaultuser@riotinto.com', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
