# Generated by Django 5.2.8 on 2025-12-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site',
            field=models.CharField(blank=True, choices=[('robevalley', 'Robe Valley'), ('greaterhopedowns', 'Greater Hope Downs'), ('restofeast', 'Rest of East'), ('restofwest', 'Rest of West')], max_length=100, null=True),
        ),
    ]
