# Generated by GitHub Copilot: Remove email field from User model
from django.db import migrations


def remove_email_field(apps, schema_editor):
    User = apps.get_model("login", "User")
    if "email" in [f.name for f in User._meta.get_fields()]:
        schema_editor.remove_field(User, User._meta.get_field("email"))


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0008_alter_user_site"),
    ]
    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
